language: php

php:
  - 5.5

env:

# Enable faster builds using the new container-based infrastructure
sudo: false

cache:
  bundler: true
  directories:
    - vendor

install:
  - composer install --dev  --no-interaction

script:
  - ./phplint.sh
  - vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml
after_success:
  - travis_retry php vendor/bin/coveralls -v